name: deploy
on: push
jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v17.2
      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
          done
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: contains(steps.changed-files.outputs.modified_files, 'docker/image.dockerfile')
      - name: build and push to docker vim with latex
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/ros2-tutorial
          file: docker/image.dockerfile
          push: true
        if: contains(steps.changed-files.outputs.modified_files, 'docker/image.dockerfile')
